import type { PrismaClient } from "@prisma/client"

export async function clean(prisma: PrismaClient) {
  console.log("  Clearing existing data...")

  // Delete in reverse FK order to avoid constraint violations
  await prisma.auditLog.deleteMany()
  await prisma.aIUsageRecord.deleteMany()
  await prisma.aICredit.deleteMany()
  await prisma.reportSchedule.deleteMany()
  await prisma.caseSupply.deleteMany()
  await prisma.caseProcedure.deleteMany()
  await prisma.case.deleteMany()
  await prisma.surgeonUsage.deleteMany()
  await prisma.invoiceLineItem.deleteMany()
  await prisma.invoice.deleteMany()
  await prisma.pOLineItem.deleteMany()
  await prisma.purchaseOrder.deleteMany()
  await prisma.crossVendorTieInMember.deleteMany()
  await prisma.crossVendorTieIn.deleteMany()
  await prisma.alert.deleteMany()
  await prisma.contractChangeProposal.deleteMany()
  await prisma.pendingContract.deleteMany()
  await prisma.contractDocument.deleteMany()
  await prisma.contractPricing.deleteMany()
  await prisma.contractTier.deleteMany()
  await prisma.contractTermProcedure.deleteMany()
  await prisma.contractTerm.deleteMany()
  await prisma.contractPeriod.deleteMany()
  await prisma.rebate.deleteMany()
  await prisma.payment.deleteMany()
  await prisma.credit.deleteMany()
  await prisma.contractFacility.deleteMany()
  await prisma.contract.deleteMany()
  await prisma.cOGRecord.deleteMany()
  await prisma.pricingFile.deleteMany()
  await prisma.vendorNameMapping.deleteMany()
  await prisma.productBenchmark.deleteMany()
  await prisma.payorContract.deleteMany()
  await prisma.connection.deleteMany()
  await prisma.featureFlag.deleteMany()
  await prisma.member.deleteMany()
  await prisma.session.deleteMany()
  await prisma.account.deleteMany()
  await prisma.user.deleteMany()
  await prisma.organization.deleteMany()
  await prisma.vendorDivision.deleteMany()
  await prisma.vendor.deleteMany()
  await prisma.productCategory.deleteMany()
  await prisma.facility.deleteMany()
  await prisma.healthSystem.deleteMany()

  console.log("  Clean: all tables cleared")
}
