/**
 * MACRS (Modified Accelerated Cost Recovery System) depreciation schedule.
 *
 * This module implements the IRS 5-year property / half-year convention
 * schedule as published in IRS Publication 946, Table A-1. The half-year
 * convention assumes that property is placed in service at the midpoint
 * of the first taxable year, which is why the first-year rate (20%) is
 * lower than the second-year rate (32%) and the schedule runs for 6
 * taxable years even though the recovery period is only 5.
 */

/**
 * IRS Publication 946 Table A-1: 5-year property, half-year convention.
 *
 * Percentages are expressed as decimals (0.20 = 20%). The six values sum
 * to exactly 1.0 so the asset is fully depreciated by end-of-year-6.
 */
export const MACRS_5Y_HALF_YEAR: readonly number[] = [
  0.2,
  0.32,
  0.192,
  0.1152,
  0.1152,
  0.0576,
]

export interface DepreciationEntry {
  /** 1-indexed taxable year. */
  year: number
  /** IRS table percentage for the year, expressed as a decimal. */
  depreciationPercent: number
  /** Dollar depreciation taken in this year (capitalCost × percent). */
  depreciationAmount: number
  /** Running total of depreciation taken through this year. */
  cumulativeDepreciation: number
  /** Remaining book value = capitalCost − cumulativeDepreciation. */
  bookValue: number
  /** Tax savings generated by the depreciation deduction = depreciationAmount × taxRate. */
  taxSavings: number
}

export interface BuildMacrsScheduleInput {
  /** Original cost basis of the capital asset, in dollars. */
  capitalCost: number
  /** Marginal tax rate as a decimal (0.21 = 21%). */
  taxRate: number
}

/**
 * Build a MACRS 5-year half-year-convention depreciation schedule.
 *
 * Formulas (for year t, 1-indexed):
 *   depreciationAmount[t]      = capitalCost × MACRS_5Y_HALF_YEAR[t-1]
 *   cumulativeDepreciation[t]  = Σ depreciationAmount[1..t]
 *   bookValue[t]               = capitalCost − cumulativeDepreciation[t]
 *   taxSavings[t]              = depreciationAmount[t] × taxRate
 *
 * Returns exactly 6 entries. A zero `capitalCost` returns six
 * all-zero entries rather than an empty array so downstream code can
 * always rely on a stable shape.
 */
export function buildMacrsSchedule(
  input: BuildMacrsScheduleInput,
): DepreciationEntry[] {
  const { capitalCost, taxRate } = input
  const schedule: DepreciationEntry[] = []
  let cumulative = 0

  for (let i = 0; i < MACRS_5Y_HALF_YEAR.length; i++) {
    const percent = MACRS_5Y_HALF_YEAR[i] as number
    const amount = capitalCost * percent
    cumulative += amount
    schedule.push({
      year: i + 1,
      depreciationPercent: percent,
      depreciationAmount: amount,
      cumulativeDepreciation: cumulative,
      bookValue: capitalCost - cumulative,
      taxSavings: amount * taxRate,
    })
  }

  return schedule
}
