import { describe, expect, it, vi, beforeEach } from "vitest"
import {
  buildCsv,
  buildLegacyXls,
  buildXlsx,
  cogFixtureRows,
  cogMatrix,
  COG_HEADER,
} from "../support/upload-fixtures"

const getSession = vi.fn()

vi.mock("@/lib/auth-server", () => ({
  auth: { api: { getSession: (args: unknown) => getSession(args) } },
}))
vi.mock("next/headers", () => ({ headers: vi.fn(async () => new Headers()) }))

let userSeq = 0
beforeEach(() => {
  userSeq += 1
  getSession.mockResolvedValue({ user: { id: `parse-user-${userSeq}` } })
})

import { POST } from "@/app/api/parse-file/route"

type ParseResponse = {
  headers?: string[]
  rows?: Record<string, string>[]
  headerRowIndex?: number
  error?: string
}

async function upload(name: string, bytes: Buffer | Uint8Array, type = "application/octet-stream") {
  const form = new FormData()
  form.append("file", new File([new Uint8Array(bytes)], name, { type }))
  const res = await POST(new Request("http://localhost/api/parse-file", { method: "POST", body: form }))
  return { status: res.status, body: (await res.json()) as ParseResponse }
}

const XLSX_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

describe("/api/parse-file", () => {
  it("rejects unauthenticated callers", async () => {
    getSession.mockResolvedValue(null)
    const { status } = await upload("cog.xlsx", await buildXlsx(cogMatrix(cogFixtureRows(3))), XLSX_TYPE)
    expect(status).toBe(401)
  })

  it("rejects a request with no file", async () => {
    const res = await POST(new Request("http://localhost/api/parse-file", { method: "POST", body: new FormData() }))
    expect(res.status).toBe(400)
  })

  it("parses a plain .xlsx into headers and one object per data row", async () => {
    const rows = cogFixtureRows(25)
    const { status, body } = await upload("cog.xlsx", await buildXlsx(cogMatrix(rows)), XLSX_TYPE)
    expect(status).toBe(200)
    expect(body.headers).toEqual(COG_HEADER)
    expect(body.rows).toHaveLength(25)
    expect(body.rows![0]!["PO Number"]).toBe(rows[0]!.po)
    expect(body.rows![24]!["Vendor Item No"]).toBe(rows[24]!.vendorItemNo)
  })

  it("finds the header row below report title rows", async () => {
    const { body } = await upload(
      "titled.xlsx",
      await buildXlsx(cogMatrix(cogFixtureRows(10)), {
        titleRows: ["Lighthouse Surgical Center", "COG Export — Q3 2026", "Generated by ERP"],
      }),
      XLSX_TYPE,
    )
    expect(body.headers).toEqual(COG_HEADER)
    expect(body.headerRowIndex).toBe(3)
    expect(body.rows).toHaveLength(10)
  })

  it("flattens rich-text, hyperlink, and formula cells to their visible values", async () => {
    const rows = cogFixtureRows(8)
    const { body } = await upload(
      "styled.xlsx",
      await buildXlsx(cogMatrix(rows), {
        richTextColumn: 3,
        hyperlinkColumn: 2,
        formulaColumn: { index: 8, sourceA: 6, sourceB: 7 },
      }),
      XLSX_TYPE,
    )
    const serialized = JSON.stringify(body.rows)
    expect(serialized).not.toContain("[object Object]")
    expect(body.rows![0]!["Description"]).toBe(rows[0]!.description)
    expect(body.rows![0]!["Vendor Item No"]).toBe(rows[0]!.vendorItemNo)
    expect(Number(body.rows![0]!["Extended Price"])).toBeCloseTo(rows[0]!.quantity * rows[0]!.unitCost, 2)
  })

  it("drops a phantom tail of thousands of near-empty rows", async () => {
    const { body } = await upload(
      "phantom.xlsx",
      await buildXlsx(cogMatrix(cogFixtureRows(40)), { phantomTailRows: 5_000, phantomTailColumn: 0 }),
      XLSX_TYPE,
    )
    expect(body.rows).toHaveLength(40)
  })

  it("parses a legacy BIFF .xls through the SheetJS path", async () => {
    const rows = cogFixtureRows(12)
    const { status, body } = await upload(
      "legacy.xls",
      buildLegacyXls(cogMatrix(rows), ["Legacy ERP export"]),
      "application/vnd.ms-excel",
    )
    expect(status).toBe(200)
    expect(body.headers).toEqual(COG_HEADER)
    expect(body.rows).toHaveLength(12)
    expect(body.rows![11]!["PO Number"]).toBe(rows[11]!.po)
  })

  it("explains a CSV that was renamed to .xlsx", async () => {
    const { status, body } = await upload("renamed.xlsx", buildCsv(cogMatrix(cogFixtureRows(3))), XLSX_TYPE)
    expect(status).toBe(400)
    expect(body.error).toMatch(/rename the extension to \.csv/i)
  })

  it("parses a multi-megabyte, 40,000-row workbook completely", async () => {
    const rows = cogFixtureRows(40_000, 7)
    const bytes = await buildXlsx(cogMatrix(rows))
    expect(bytes.byteLength).toBeGreaterThan(1_500_000)
    const started = Date.now()
    const { status, body } = await upload("large.xlsx", bytes, XLSX_TYPE)
    expect(status).toBe(200)
    expect(body.rows).toHaveLength(40_000)
    expect(body.rows![39_999]!["PO Number"]).toBe(rows[39_999]!.po)
    expect(Date.now() - started).toBeLessThan(60_000)
  }, 120_000)

  it("refuses a file over 100 MB with the size in the message", async () => {
    const big = new File([new Uint8Array(1)], "huge.xlsx", { type: XLSX_TYPE })
    Object.defineProperty(big, "size", { value: 101 * 1024 * 1024 })
    const form = new FormData()
    form.append("file", big)
    const req = new Request("http://localhost/api/parse-file", { method: "POST" })
    Object.defineProperty(req, "formData", { value: async () => form })
    const res = await POST(req)
    expect(res.status).toBe(400)
    expect(((await res.json()) as ParseResponse).error).toMatch(/101\.0MB; max is 100MB/)
  })

  it("rate-limits a single user at 30 parses per minute", async () => {
    getSession.mockResolvedValue({ user: { id: "parse-rate-limit-user" } })
    const bytes = await buildXlsx(cogMatrix(cogFixtureRows(2)))
    const statuses: number[] = []
    for (let i = 0; i < 31; i++) statuses.push((await upload("r.xlsx", bytes, XLSX_TYPE)).status)
    expect(statuses.slice(0, 30).every((s) => s === 200)).toBe(true)
    expect(statuses[30]).toBe(429)
  }, 120_000)
})
